name: "Go Protobuf Generation"
on:
  push:
    tags:
      - '*'
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment", "shipping"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - uses: actions/checkout@v4
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Golang Protoc"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com